// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adjhzcafcqfjvtfragsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkamh6Y2FmY3FmanZ0ZnJhZ3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDQ2NzcsImV4cCI6MjA2MTAyMDY3N30.x7z6rALSF7pzgpdI5Fb8FclWzmKFqQVPe1oxpv4Ucwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);